// This file has been generated by Specta. DO NOT EDIT.

export type ArenaChannelInfo = { id: number; title: string; slug: string; length: number; status: string }

export type ArticleAudioState = { status: ArticleAudioStatus; audio_path: string | null; duration_ms: number | null; last_position_ms: number; completed_at: string | null }

export type ArticleAudioStatus = "absent" | "ready"

/**
 * The type of content a block represents.
 */
export type BlockType = "image" | "article" | "link" | "video" | "file" | "channel"

/**
 * Runtime card category derived from the Markdown document shape.
 *
 * `type` remains legacy source metadata in frontmatter. Feed/detail rendering
 * should use this derived category instead. Body shape remains primary, while
 * ownership metadata distinguishes bodyless media from metadata-only links.
 */
export type CardKind = "article" | "media" | "link" | "channel"

/**
 * Serializable channel data for the frontend.
 */
export type ChannelDto = { tag: string; description: string | null; color: string | null; icon: string | null; position: number; created_at: string;
/**
 * Number of blocks with this tag.
 */
block_count: number }

export type ChannelPreviewsSnapshot = { generation: ProjectionRevision; previews: Partial<{ [key in string]: PreviewItem[] }> }

export type ClipperBrowserStatus = { label: string;
/**
 * The browser's own directory exists, so the browser is installed.
 */
detected: boolean;
/**
 * A manifest for this host is present in it.
 */
connected: boolean }

export type ClipperRecoveryItem = { id: string; kind: ClipperRecoveryKind; fileName: string; mediaPath: string | null; size: number; createdAt: string }

export type ClipperRecoveryKind = "pending_upload"

export type ClipperSetupStatus = {
/**
 * The host binary is installed where browsers can launch it.
 */
host_installed: boolean;
/**
 * The installed host matches the running app's version.
 */
host_current: boolean; app_version: string; browsers: ClipperBrowserStatus[] }

export type CommandError = { kind: "no_vault" } | { kind: "internal"; message: string }

export type CreateBlockParams = { block_type: string; title: string | null; url: string | null; tags: string[]; file_path: string | null }

export type CreateMediaAssetCardParams = { media_ref: string; target_tag: string; source_slug: string | null }

export type DeleteBlockMedia = { path: string; file_name: string; kind: DeleteMediaAssetKind; referenced_by: string[] }

export type DeleteBlockPlan = { slug: string; markdown_file: string; unused_media: DeleteBlockMedia[]; shared_media: DeleteBlockMedia[] }

export type DeleteMediaAssetKind = "image" | "video" | "audio" | "document" | "file"

export type DeleteMediaAssetPlan = { media_ref: string; media_kind: DeleteMediaAssetKind; referenced_by: MediaAssetReferenceBlock[] }

export type DeleteOrphanResult = { deleted: string[]; skipped: string[] }

export type DeleteTextSelectionParams = { source_slug: string; selected_text: string; first_block_start: number; first_block_end: number; source_body_hash: string }

export type ExtractInlineMediaParams = { source_slug: string; media_ref: string; target_tag: string }

export type ExtractTextSelectionParams = { source_slug: string; target_tag: string; selected_text: string; first_block_start: number; first_block_end: number; source_body_hash: string }

export type FeedPlaybackContainer = "mp4" | "webm"

export type FeedPlaybackDescriptor = { kind: FeedPlaybackKind; source_path: string; poster_preview_path: string; width: number | null; height: number | null; container: FeedPlaybackContainer; profile: FeedPlaybackProfile }

export type FeedPlaybackKind = "single_video"

export type FeedPlaybackProfile = "standard" | "heavy"

export type FeedPreviewKind = "text" | "image" | "video_poster" | "composite"

/**
 * Preview plan for one card.
 *
 * Same split as [`FeedPreviewTile`]: `width`/`height` are the source,
 * `preview_width`/`preview_height` are the artifact the feed paints. Absent
 * preview dimensions mean "geometry not known yet" — a legitimate state for
 * formats Rust cannot decode — and must never be substituted with a default
 * aspect.
 */
export type FeedPreviewManifest = { kind: FeedPreviewKind; primary_preview_path: string | null; width: number | null; height: number | null; preview_width?: number | null; preview_height?: number | null; tiles: FeedPreviewTile[]; overflow_count: number }

/**
 * One preview tile.
 *
 * `width`/`height` describe the **source** file and exist for playback
 * budgets. `preview_width`/`preview_height` describe the **derived artifact**
 * this tile actually paints and are the only legitimate input to card
 * geometry. For composite previews the two differ by design: collage tiles are
 * cropped to fixed slots. See `SPEC_CARD_MEDIA_GEOMETRY.md`.
 */
export type FeedPreviewTile = { source_path: string; preview_path: string | null; width: number | null; height: number | null; preview_width?: number | null; preview_height?: number | null; is_video: boolean; is_video_poster: boolean }

/**
 * What a folder holds, before it becomes a space.
 */
export type FolderPreview = { markdown_files: number; media_files: number; other_files: number }

export type GraphLink = { id: string; kind: GraphLinkKind; source: string; target: string; directed: boolean; count: number; target_ref: string | null }

export type GraphLinkKind = "collection_membership" | "wikilink" | "related_note"

export type GraphNode = { id: string; kind: GraphNodeKind; label: string; slug: string | null; collection_ref: string | null; card_kind: CardKind | null; block_type: BlockType | null; thumbnail: string | null; preview_manifest: string | null; degree: number }

export type GraphNodeKind = "card" | "collection"

export type GraphOptions = { include_collections: boolean; include_wikilinks: boolean; include_related_notes: boolean; materialize_large_library: boolean }

export type GraphScope = { kind: GraphScopeKind; collection_ref: string | null }

export type GraphScopeKind = "current_route" | "library"

export type GraphSnapshot = { generation: ProjectionRevision; nodes: GraphNode[]; links: GraphLink[]; total_cards: number; total_collections: number; current_collection: string | null; truncated: boolean; truncation_reason: GraphTruncationReason | null; can_materialize_full: boolean; visible_nodes: number; visible_links: number; total_nodes: number; total_links: number }

export type GraphTruncationReason = "large_library"

export type GridSnapshot = { generation: ProjectionRevision; blocks: LightBlock[]; total_blocks: number; has_more: boolean }

export type IcloudDownloadProgress = { status: IcloudDownloadStatus;
/**
 * 0–100 when the metadata reports one. Never invented.
 */
percent: number | null }

export type IcloudDownloadStatus =
/**
 * Contents are on this Mac; the percent is trivially 100.
 */
"current" |
/**
 * The system is bringing the contents down right now.
 */
"downloading" |
/**
 * Evicted and no download in flight.
 */
"not_downloaded" |
/**
 * The file is not managed by iCloud at all.
 */
"not_managed" |
/**
 * The metadata gave no answer within the helper's deadline. The caller
 * keeps its numberless indicator — an honest "unknown" over a stale bar.
 */
"unknown"

export type ImportChannelRequest = { slug: string; tag: string }

/**
 * Result of importing a single channel.
 */
export type ImportChannelResult = { channel_slug: string; channel_title: string; imported: number; skipped: number; errors: string[] }

/**
 * Progress update for a single block import.
 */
export type ImportProgress = { channel_slug: string; current: number; total: number; block_title: string | null }

/**
 * A block as read from the database index.
 */
export type IndexedBlock = { id: number; slug: string; block_type: BlockType; card_kind: CardKind; title: string | null; content_heading: string | null; display_title: string | null; fallback_label: string; description: string | null; url: string | null; media_file: string | null; thumbnail: string | null; saved_at: string; source: string | null; width: number | null; height: number | null; author: string | null; body: string; preview_text: string | null; first_image: string | null; media_urls: string | null; media_dimensions: string | null; preview_manifest: string | null; feed_playback: string | null; thumb_format: ThumbFormat | null; thumb_mtime: number; related_notes: string[]; body_hash: string | null; origin: string | null; index_warning: string | null; tags: string[] }

export type InlineMediaExtractError = { kind: "no_vault" } | { kind: "source_not_found"; source_slug: string } | { kind: "source_not_article"; source_slug: string; block_type: string } | { kind: "invalid_media_ref"; reason: string } | { kind: "media_not_referenced"; media_ref: string; source_slug: string } | { kind: "media_not_found"; media_ref: string } | { kind: "unsupported_media_type"; media_ref: string } | { kind: "internal"; message: string }

/**
 * A lightweight block for list/grid views. Body is truncated (max 500 chars),
 * description is omitted, source is omitted.
 */
export type LightBlock = { id: number; slug: string; block_type: BlockType; card_kind: CardKind; title: string | null; content_heading: string | null; display_title: string | null; fallback_label: string; url: string | null; media_file: string | null; thumbnail: string | null; saved_at: string; width: number | null; height: number | null; author: string | null; body: string; preview_text: string | null; first_image: string | null; media_urls: string | null; media_dimensions: string | null; preview_manifest: string | null; feed_playback: string | null;
/**
 * The card's own media exists, but iCloud is holding its contents.
 *
 * Only ever true while a preview could not be built: once a preview
 * exists the card draws from it and no longer cares where the original
 * lives. See SPEC_CLOUD_STORAGE.md Х5–Х6.
 */
content_in_cloud?: boolean; search_match: SearchMatch | null }

export type MediaAssetActionError = { kind: "no_vault" } | { kind: "invalid_media_ref"; reason: string } | { kind: "media_not_found"; media_ref: string } | { kind: "unsupported_media_kind"; media_ref: string } | { kind: "name_taken"; target: string } | { kind: "invalid_filename"; reason: string } | { kind: "clipboard_unsupported"; media_ref: string } | { kind: "internal"; message: string }

export type MediaAssetMutationResult = { media_ref: string; new_media_ref: string | null; affected_slugs: string[] }

export type MediaAssetReferenceBlock = { slug: string; title: string | null; display_title: string | null; fallback_label: string; card_kind: CardKind; reference_kinds: string[] }

export type MediaAssetReferenceKind = "frontmatter_file" | "body_embed"

export type MergeBlocksError = { kind: "no_vault" } | { kind: "too_few_cards" } | { kind: "duplicate_slug"; slug: string } | { kind: "block_not_found"; slug: string } | { kind: "block_not_mergeable"; slug: string; block_type: string } | { kind: "invalid_slug"; slug: string; reason: string } | { kind: "reference_rewrite_failed"; path: string; message: string } | { kind: "internal"; message: string }

export type MergeBlocksResult = { block: IndexedBlock; merged_slug: string; removed_slugs: string[] }

export type NativeShellSmokeReport = { status: string; vault_path: string | null; location: string; user_agent: string; timestamp_ms: number }

export type OrphanMedia = { file_name: string; size_bytes: number; modified_secs: number }

export type OrphanMediaBatchRequest = { file_names: string[] }

/**
 * Sidebar preview: slug + whether it's a text-only thumbnail (for dark mode invert).
 */
export type PreviewItem = { slug: string;
/**
 * True for text-only articles (baked text thumbnail needs CSS invert in dark mode).
 */
text: boolean;
/**
 * Unix timestamp (seconds) of the thumb file's last modification.
 * Frontend uses this as a cache-buster (`?m=<mtime>`) so the browser
 * refetches when the file changes on disk (e.g. Phase 2 worker
 * overwrites a PNG placeholder with a decoded JPEG).
 */
mtime: number;
/**
 * True if the thumb file exists on disk. False means the block was
 * just saved and Phase 1/2 hasn't produced a thumb yet. Frontend
 * renders a neutral placeholder tile for `has_thumb=false` so the
 * card never collapses to empty space. Renamed from camelCase at
 * the serde boundary via the struct default (snake_case in JSON).
 */
has_thumb: boolean }

export type ProjectionRevision = number

export type PromoteOrphanResult = { created: IndexedBlock[]; skipped: string[] }

export type RecoveredClipperBlock = { slug: string }

export type RemoveMediaAssetFromCardParams = { media_ref: string; source_slug: string; reference_kind: MediaAssetReferenceKind; occurrence_index: number | null }

export type RenameBlockError = { kind: "no_vault" } | { kind: "block_not_found"; slug: string } | { kind: "invalid_filename"; reason: string } | { kind: "name_taken"; requested: string } | { kind: "internal"; message: string }

export type RenameBlockResult = { old_slug: string; new_slug: string }

export type RenameMediaAssetParams = { media_ref: string; new_stem: string }

/**
 * Result of a full vault scan.
 */
export type ScanResult = {
/**
 * Number of blocks successfully indexed.
 */
indexed: number;
/**
 * Number of files that failed to parse.
 */
errors: number }

export type SearchMatch = { field: SearchMatchField; kind: SearchMatchKind; excerpt: string; ranges: SearchTextRange[]; score: number; explanation: string | null }

export type SearchMatchField = "title" | "description" | "author" | "body" | "url" | "semantic"

export type SearchMatchKind = "exact" | "prefix" | "fuzzy" | "alias" | "semantic"

export type SearchPageToken = { projection_revision: ProjectionRevision; search_revision: SearchRevision; offset: number; query_fingerprint: string }

export type SearchRevision = number

export type SearchSnapshot = { generation: ProjectionRevision; search_generation: SearchRevision; blocks: LightBlock[]; has_more: boolean; next_cursor: SearchPageToken | null; cursor_reset: boolean }

export type SearchTextRange = { start: number; end: number }

export type SpaceStats = { file_count: number; markdown_count: number; media_count: number; total_bytes: number;
/**
 * From the space's local derived index; `None` when the space has never
 * been opened (no vault-id / no index) or the index predates `card_kind`.
 */
element_count: number | null;
/**
 * Files whose contents iCloud is currently holding rather than keeping on
 * this Mac. The number behind the settings explanation (SPEC_CLOUD_STORAGE.md Х20).
 */
offloaded_count: number }

/**
 * A tag with its usage count across blocks.
 */
export type TagCount = { tag: string; count: number }

export type TaxonomySnapshot = { generation: ProjectionRevision; tags: TagCount[]; channels: ChannelDto[]; total_blocks: number }

export type TextSelectionExtractError = { kind: "no_vault" } | { kind: "source_not_found"; source_slug: string } | { kind: "source_not_article"; source_slug: string; block_type: string } | { kind: "empty_selection" } | { kind: "stale_selection" } | { kind: "unsupported_selection_shape"; reason: string } | { kind: "unsafe_source_patch"; reason: string } | { kind: "invalid_collection_ref"; reason: string } | { kind: "internal"; message: string }

export type ThumbFormat = "jpeg" | "png"

/**
 * A space that is bound but not reachable right now.
 */
export type UnavailableVault = { path: string }

export type VaultOpenResult = { indexed: number; errors: number; sync_in_progress: boolean; derived_store_ready: boolean; bootstrapped_from_legacy: boolean; migration_required: boolean; thumbs_root: string }

export type VaultStats = { totalFileCount: number; markdownFileCount: number; mediaFileCount: number; sourceBytes: number; currentCollectionCardCount: number; currentCollection: string | null; updatedAtMs: number }

export type VaultWriteLayoutDto = { cards: string; media: string; collections: string }
